.\"	$Id: mdl.1,v 1.7 2015/10/07 20:00:49 je Exp $
.\"
.\" Copyright (c) 2015 Juha Erkkilä <je@turnipsi.no-ip.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\" The following requests are required for all man pages.
.\"
.Dd $Mdocdate: October 7 2015 $
.Dt MDL 1
.Os
.Sh NAME
.Nm mdl
.Nd a music description language with a midi sequencer
.Sh SYNOPSIS
.Nm mdl
.Op Fl cs
.Op Fl d Ar mdl-directory
.Op Ar
.Sh DESCRIPTION
.Nm
interprets music files
and plays them through a midi device.
Syntax mimicks the
.Xr lilypond 1
syntax but is not compatible.
.Pp
When
.Fl s
option is specified,
.Nm
is started in server mode,
when it also listens on a UNIX-domain socket
for incoming music scripts.
Whenever a music script is received,
the music that is currently playing
is replaced by the music described by the received script.
If all files have been played,
or no files were given as command line arguments,
.Nm
continues to run waiting for more music scripts on socket.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c
Send music description to server (act as client only).
.It Fl d Ar mdl-directory
Use
.Ar mdl-directory
as the directory to keep a listening socket.
Setting this option allows running multiple instances of
.Nm
even when
.Ar -s
option is set.
.It Fl s
Open a listening socket to accept music descriptions (server-mode).
.El
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.Sh FILES
.Bl -tag -width ~/.mdl/socket -compact
.It Pa ~/.mdl
the default mdl-directory
.It Pa ~/.mdl/socket
the default listening socket path
.El
.Sh EXIT STATUS
The
.Nm
utility exits 0 on success, and >0 if an error occurs.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.Sh SEE ALSO
.Xr lilypond 1
.\" .Sh STANDARDS
.\" .Sh HISTORY
.Sh AUTHORS
.An Juha Erkkilä Aq Mt je@turnipsi.no-ip.org
.\" .Sh CAVEATS
.\" .Sh BUGS
