.\"	$Id: mdl.1,v 1.14 2016/05/07 20:24:59 je Exp $
.\"
.\" Copyright (c) 2015 Juha Erkkilä <je@turnipsi.no-ip.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\" The following requests are required for all man pages.
.\"
.Dd $Mdocdate: May 7 2016 $
.Dt MDL 1
.Os
.Sh NAME
.Nm mdl
.Nd a music description language with a MIDI sequencer
.Sh SYNOPSIS
.Nm mdl
.Op Fl nsv
.Op Fl d Ar debuglevel
.Op Fl f Ar device
.Op Fl m Ar MIDI-interface
.Op Ar
.Sh DESCRIPTION
.Nm
interprets music files
and plays them through a MIDI device.
Syntax mimicks the
.Xr lilypond 1
syntax but is not compatible.
.Pp
When
.Fl s
option is specified,
.Nm
is started in server mode,
when it also listens on a UNIX-domain socket
for incoming music scripts.
Whenever a music script is received,
the music that is currently playing
is replaced by the music described by the received script.
If all files have been played,
or no files were given as command line arguments,
.Nm
continues to run waiting for more music scripts on socket.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c
Send music description to server (act as client only).
.It Fl d Ar debuglevel
Set
.Ar debuglevel
to some value.
Supported values are numbers from from 0 to 4,
where a bigger number means
more detailed debugging messages are printed.
Other possible values are
.Cm clock ,
.Cm exprconv ,
.Cm joins ,
.Cm midi ,
.Cm midistream ,
.Cm mm ,
.Cm parsing ,
.Cm process ,
.Cm relative
and
.Cm song .
Several options may be set by separating them with a comma,
for example
.Dq joins,midi .
.It Fl f Ar device
Sets the MIDI device path.
Interpretation for this depends on the MIDI-interface used.
For
.Cm raw
MIDI devices this the file path with the default value of
.Dq /dev/rmidi0 .
For
.Cm sndio
MIDI devices this is the name of the
.Xr sndio 7
MIDI device with the default value of
.Dq default .
See the
.Ar -m
option for setting the MIDI-interface type.
.It Fl m Ar MIDI-interface
Set the
.Ar MIDI-Interface
type
.Nm
uses.
Possible values are
.Cm raw
and
.Cm sndio ,
but not all options may have been compiled in.
See the
.Ar -v
option for supported MIDI-interfaces
and the default MIDI-interface type used.
.It Fl n
Dry run.
Do everything else but do not actually play music.
.It Fl s
Open a listening socket to accept music descriptions (server-mode).
.It Fl v
Show
.Nm
version and the supported MIDI interfaces
.Nm
was compiled with.
.El
.\" .Sh ENVIRONMENT
.\" For sections 1, 6, 7, and 8 only.
.Sh FILES
.Bl -tag -width ~/.mdl/socket -compact
.It Pa ~/.mdl
the default mdl-directory
.It Pa ~/.mdl/socket
the default listening socket path
.El
.Sh EXIT STATUS
The
.Nm
utility exits 0 on success, and >0 if an error occurs.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.Sh SEE ALSO
.Xr lilypond 1 ,
.Xr mdl 5
.\" .Sh STANDARDS
.\" .Sh HISTORY
.Sh AUTHORS
.An Juha Erkkilä Aq Mt je@turnipsi.no-ip.org
.\" .Sh CAVEATS
.\" .Sh BUGS
